### Site Settings ###
title               : Daniele Di Giamberardino
description         : >-
                      Sono un Automation Engineer focalizzato su GNC, controllo predittivo e Digital Twin, con una forte attrazione per i sistemi aerospace, automotive e di difesa.
                      I progetti che trovi qui nascono dalla convinzione che modellistica rigorosa e approcci data-driven non siano alternativi, ma complementari. 
                      Sto cercando un contesto in cui progettare sistemi di guida e controllo per applicazioni ad alto impatto.
google_analytics: "G-QBWX4PKYT5"
complesse.baseurl             : ""            
repository          : danieledigiamberardino/danieledigiamberardino.github.io
remote_theme        : yousinix/portfolYOU
open_new_tab        : false                    

### Plugins ###
plugins:
  - jemoji

### Navbar Settings ###
nav_exclude:                                            
  - pages/tags.html
  - pages/404.html
  - pages/index.md
  - documentation/partials/**
  ### Author Info ###
author:
  name              : Daniele Di Giamberardino
  image             : "../96dd2b5e-a9bd-4cfd-b4f2-0fe1bf26e44c.jpg"
  email             : danieledigiambi@gmail.com
  github            : danieledigiamberardino
  linkedin          : daniele-di-giamberardino-37460a274

### Posts ###
permalink: /blog/:title

### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name

### Defaults for collections ###
defaults:
  - scope:
      path: "projects"
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false                                   

### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
