### Site Settings ###
title               : Daniele Di Giamberardino
description         : >-
                      Ingegnere dell'Automazione specializzato in controlli predittivi (MPC), machine learning e modellistica dinamica. In questo spazio condivido i miei progetti pratici, dallo sviluppo di Digital Twin alla stabilizzazione aerospaziale. Sono alla ricerca di un'opportunità di inserimento in R&D per applicare metodologie data-driven a sfide industriali complesse.baseurl             : ""            
repository          : danieledigiamberardino/danieledigiamberardino.github.io
remote_theme        : yousinix/portfolYOU
open_new_tab        : false                    

### Plugins ###
plugins:
  - jemoji

### Navbar Settings ###
nav_exclude:                                            
  - pages/tags.html
  - pages/404.html
  - pages/index.md
  - documentation/partials/** ### Author Info ###
author:
  name              : Daniele Di Giamberardino
  image             : ""
  email             : danieledigiambi@gmail.com
  github            : danieledigiamberardino
  linkedin          : daniele-di-giamberardino-37460a274

### Posts ###
permalink: /blog/:title

### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name

### Defaults for collections ###
defaults:
  - scope:
      path: "projects"
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false                                   

### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
